// Copyright (c) 2021 Graphcore Ltd. All rights reserved.
#ifndef POPTORCH_CODEGEN_POPTORCH_DIALECT_IR_H_
#define POPTORCH_CODEGEN_POPTORCH_DIALECT_IR_H_

// Include generic helpers
// (This also ncludes mlir/IR/Dialect.h needed for PoptorchDialect.h.inc)
#include "dialect/Helpers.hpp"

// Include op specific helpers
#include "dialect/ops/NormOpsHelpers.hpp"
#include "dialect/ops/ReductionsHelpers.hpp"

// Include the dialect generated by tablegen (PoptorchDialect.td)
#include "dialect/PoptorchDialect.h.inc"

// Include everything else
#include "Poptorch.hpp"

#endif // POPTORCH_CODEGEN_POPTORCH_DIALECT_IR_H_
