set(POPLAR_INSTALL_DIR "" CACHE STRING "The Poplar install directory")
list(APPEND POPTORCH_CMAKE_ARGS -DPOPLAR_INSTALL_DIR=${POPLAR_INSTALL_DIR})

set(ENABLE_WERROR TRUE CACHE BOOL "Stop compilation on warning (-Werror)")
list(APPEND POPTORCH_CMAKE_ARGS -DENABLE_WERROR=${ENABLE_WERROR})
