set(POPLAR_INSTALL_DIR "" CACHE STRING "The Poplar install directory")
list(APPEND POPTORCH_CMAKE_ARGS -DPOPLAR_INSTALL_DIR=${POPLAR_INSTALL_DIR})

set(ENABLE_WERROR TRUE CACHE BOOL "Stop compilation on warning (-Werror)")
list(APPEND POPTORCH_CMAKE_ARGS -DENABLE_WERROR=${ENABLE_WERROR})

set(EXCLUDE_POPTORCH_LONG_TESTS OFF CACHE BOOL "Do not run Poptorch tests taking over 4min")
list(APPEND POPTORCH_CMAKE_ARGS -DEXCLUDE_LONG_TESTS=${EXCLUDE_POPTORCH_LONG_TESTS})
