#ifndef INCLUDE_POPTORCH_OP_BUILDER_HPP
#define INCLUDE_POPTORCH_OP_BUILDER_HPP

#include <string>
#include <vector>

namespace torch {
namespace jit {
class Graph;
class Node;
class Value;
} // namespace jit
} // namespace torch

namespace poptorch {

// Manually added.
torch::jit::Node *CreateReshape(torch::jit::Graph &graph, torch::jit::Value *A,
                                const std::vector<int64_t> &new_shape);

// Autogenerated.
#include "CompilerOps.h.inc"

} // namespace poptorch

#endif // INCLUDE_POPTORCH_OP_BUILDER_HPP
