// Copyright (c) 2020 Graphcore Ltd. All rights reserved.
#ifndef INCLUDE_POPTORCH_OP_BUILDER_HPP
#define INCLUDE_POPTORCH_OP_BUILDER_HPP

#include <string>
#include <vector>

namespace torch {
namespace jit {
class Graph;
class Node;
class Value;
} // namespace jit
} // namespace torch

namespace poptorch {

// Manually added.
torch::jit::Node *CreateReshape(torch::jit::Graph &graph, torch::jit::Value *A,
                                const std::vector<int64_t> &new_shape);

torch::jit::Node *Create_ConstantInt(torch::jit::Graph &graph,
                                     const std::vector<int64_t> &data,
                                     const std::vector<int64_t> &new_shape);

torch::jit::Node *Create_ConstantFloat(torch::jit::Graph &graph,
                                       const std::vector<double> &data,
                                       const std::vector<int64_t> &new_shape);

// Default to int in the helper.
template <typename T> struct Create_Constant {
  torch::jit::Node *operator()(torch::jit::Graph &graph,
                               const std::vector<int64_t> &data,
                               const std::vector<int64_t> &new_shape) {
    return Create_ConstantInt(graph, data, new_shape);
  }
};

template <> struct Create_Constant<float> {
  torch::jit::Node *operator()(torch::jit::Graph &graph,
                               const std::vector<double> &data,
                               const std::vector<int64_t> &new_shape) {
    return Create_ConstantFloat(graph, data, new_shape);
  }
};

// Autogenerated.
#include "CompilerOps.h.inc"

} // namespace poptorch

#endif // INCLUDE_POPTORCH_OP_BUILDER_HPP
