[build-system]
requires = [
  "python_version>=3.7",
  "setuptools>=42",
  "wheel",
  "@PYG_DEPENDENCY@",
  "@POPTORCH_DEPENDENCY@",
  "torch-scatter",
  "torch-sparse",
  "torch-cluster",
  "torch-spline-conv"
]
build-backend = "setuptools.build_meta"
